# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to github pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
   
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing NPM
      run : npm install
    - name : Generating Build using bs
      run : npm run make
    - name : Generating web pack build
      run : npm run build
    - name : Setting github profile
      run : git config --global user.name "Adil Shaikh"
    - name : Setting email
      run : git config --global user.email "adilmas13@gmail.com"
    - name : Deploying to github page 'adilmas13.github.io/reason-react/'
      run : ./node_modules/gh-pages/bin/gh-pages.js -d build
